name: ManiaPlanet documentation
highlighter: pygments
timezone: Europe/Paris
markdown: rdiscount
url: https://anthodev.github.io/documentation/
rdiscount:
  extensions:
    - autolink      # greedily urlify links
gems:
  - jekyll-sitemap
