# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Permalinks
# permalink:        pretty

# Setup
title:            Documentation
tagline:          'for the Maniaplanet game operating system'
description:      '<a href="/"><img src="/img/maniaplanet.png"/></a>'
url:              http://www.maniaplanet.com
baseurl:          '/'
paginate:         5

author:
  name:           'Nadeo'
  url:            https://twitter.com/Maniaplanet

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/maniaplanet/documentation

gems:
  - jekyll-sitemap

# redcarpet:
#     extensions: [with_toc_data]

rdiscount:
    extensions:
      - autolink
      - generate_toc
